### ISSUE TITLE
[TASK] Buoy Detector

### ISSUE THREAD

**Issue by EirikKolas** [vortexntnu/vortex-sensor-fusion#15]
### Description of task

# Detect them Buoys!!
In the Njord challange we need to detect, classify and locate [these markers](https://njord.gitbook.io/physical-competition-2023/6-task-descriptions/6.2-sea-markers)

### Suggested Workflow

- [x] Research how best to detect them. 
  - [x] [YOLO??](https://github.com/philipperemy/yolo-9000)
- [ ] Train the damn buoy! Maybe we can get buoys from Njord? Maybe we can make our own?
- [ ] Cool Buoys don't look at explosions :sunglasses: 
- [ ] Locate all of them Buoys. A combination of:
  - [ ] Stereo Camera (If this works, it should be all we need)
  - [ ] #16 - Hard and complex problem
  - [ ] Kalman filter with the Camera as a sensor model - Easier to implement. May not be as robust as #16 as the camera has a limited fov compared to the lidar. May not be accurate as we only have the bearing of, and not the range to the object, but we can probably compensate for this by using the known size of the markers. Can be combined with the option above for more robustness

### Specifications

- [ ] Can differentiate red and green markers (1. priority)
- [ ] Can differentiate N/S/E/W markers
- [ ] Visualize and label bounding box (#17)

### Contacts

- @EirikKolas 

### Code Quality

- [ ] Every function in header files are documented (inputs/returns/exceptions)
- [ ] The project has automated tests that cover MOST of the functions and branches in functions (pytest/gtest)
- [ ] The code is documented on the wiki (provide link)
