### ISSUE TITLE
[TASK] Target Tracking

### ISSUE THREAD

**Issue by EirikKolas** [vortexntnu/vortex-sensor-fusion#18]
# Target Tracking

## Suggested Workflow
- [ ] familiarize yourself with the old target tracking [code](https://github.com/vortexntnu/vortex-cv/tree/main/tracking/scripts) 
- [ ] understand (and try) the old code
- [ ] translate the code to C++ and ROS2-humble
   - [ ] Use functions in the [filtering library](https://github.com/vortexntnu/vortex-vkf/tree/rework/bayesian-framework)
   - [ ] Look at how the EKF is implemented to get an idea of how to make the tracker use any dynamic model ans sensor model.

## Requirements
- [ ] The tracker implemetation should be able to take any dynamic model and sensor model.
- [ ] Results are easily vizualisable
- [ ] Tuning should be possible through ROS params
- [ ] A proper track manager. N/M is implemented in the old code. @hannahcl thinks it will be easier to implement an IPDA instead.
- [ ] Track Manager should be separate from the PDAF implementation 

## Contacts and Resources
@chrstrom - Expert Target Tracker Person
@hannahcl - Wrote the Python PDAF
@eirikkolas, @alekskl01 - Are taking the TTK4250 Sensor Fusion course

Fundamentals of Sensor Fusion in `Teams -> Software -> Files -> Learning Materials -> Papers and other Resources`
